#!/bin/bash
# fn_rec_pid: Internal use. Make sure it matches the same variable
#             found in whisper-auto
fn_rec_pid=/tmp/whisper-auto-rec.pid
echo "Attempting to kill $(<$fn_rec_pid)"
kill -- "$(<$fn_rec_pid)"
#kill -- -"$(<$fn_rec_pid)"
#pkill -TERM -g "$(<$fn_rec_pid)"
#pkill '^rec$'
